blank_issues_enabled: true
contact_links:
  - name: Use Discussions
    url: https://github.com/74gg/74gg.github.io/discussions
    about: If you have any questions and other, you can use Discussions.
