name: Deploy to Github Pages

on:
  push:
    branches: ["main"]

  # Probably if you remove colon, you can run it manually.
  # https://docs.github.com/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch
  # https://docs.github.com/actions/using-workflows/manually-running-a-workflow
  workflow_dispatch:

# https://docs.github.com/actions/using-jobs/assigning-permissions-to-jobs
permissions:
  contents: read
  pages: write
  id-token: write

# https://docs.github.com/actions/using-jobs/using-concurrency
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    # https://docs.github.com/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idruns-on
    # https://docs.github.com/actions/using-workflows/workflow-syntax-for-github-actions#choosing-github-hosted-runners
    runs-on: ubuntu-latest

    # https://docs.github.com/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idsteps
    steps:

      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v4

      # Github action don't have pnpm, so pnpm must be installed.
      # - https://github.com/pnpm/action-setup
      # - https://github.com/pnpm/pnpm
      #
      # The warning displayed, but no problem now.
      # - https://github.com/pnpm/action-setup/issues/99
      #
      # When this become an error, needs to install pnpm with npm or yarn.
      # - https://github.com/pnpm/action-setup/issues/99#issuecomment-1905690976
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      # What is this?
      # - name: Detect package manager
      #   id: detect-package-manager
      #   run: |
      #     echo "runner=pnpm" >> $GITHUB_OUTPUT
      #     echo $GITHUB_OUTPUT
      #     exit 0

      # https://github.com/actions/setup-node
      # https://github.com/actions/setup-node/?tab=readme-ov-file#supported-version-syntax
      # https://nodejs.org/en/about/previous-releases
      # https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "lts/iron"
          # Probably this impossible.
          # cache: pnpm

      # https://github.com/actions/configure-pages
      # https://docs.github.com/pages/getting-started-with-github-pages/using-custom-workflows-with-github-pages#configuring-the-configure-pages-action
      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          # If you images has problems, see below.
          # https://nextjs.org/docs/api-reference/next/image#unoptimized
          static_site_generator: next

      # https://github.com/actions/cache
      # https://docs.github.com/ja/actions/using-workflows/caching-dependencies-to-speed-up-workflows
      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-

      - name: Install dependencies
        run: pnpm install

      - name: Build with Next.js
        run: pnpm build

      - name: Checks all files
        run: ls -la

      # https://github.com/actions/upload-pages-artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    runs-on: ubuntu-latest

    # https://docs.github.com/actions/using-workflows/about-workflows#creating-dependent-jobs
    needs: build

    # https://github.com/74gg/74gg.github.io/deployments
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      # https://github.com/actions/deploy-pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
